apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-app

spec:
  replicas: 2

  strategy:
   type: RollingUpdate
   rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

  selector:
    matchLabels:
      app: my-app

  template:
    metadata:
      labels:
        app: my-app

    spec:
      containers:
      - name: my-app
        image: ponychan3/my-app:9e276f07172e0ffd40f10000e2af0b5480e471e7
        ports:
        - containerPort: 80